# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'xoso98.com' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for xoso98.com
  platform :ios, '8.0'
  pod 'Firebase/Core', '~> 5.3.0'

  target 'xoso98.comTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'xoso98.com-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for xoso98.com-tvOS

  target 'xoso98.com-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
